name: Kernel Build Munch

on:
  workflow_dispatch:
    inputs:
      KERNEL_TREE:
        description: "Kernel Tree"
        default: "https://github.com/olzhas0986/kernel_xiaomi_sm8250"
        required: true
      KERNEL_TREE_BRANCH:
        description: "Kernel Tree Branch"
        required: true
        default: "base-munch"

      ADD_KERNELSU:
        description: "Add KernelSU"
        type: boolean
        default: true
      KERNELSU_SETUP_URL:
        description: "KernelSU setup.sh URL"
        required: false
        default: "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/refs/heads/next/kernel/setup.sh"
      KERNELSU_SETUP_BRANCH:
        description: "KernelSU Branch"
        required: false
        default: "next"

      CREATE_ANYKERNEL:
        description: "Create AnyKernel"
        type: boolean
        default: true
      ANYKERNEL_URL:
        description: "AnyKernel URL"
        default: "https://github.com/Impqxr/AKmunch"
        required: false
      ANYKERNEL_BRANCH:
        description: "AnyKernel Branch"
        default: "main"
        required: false
      ANYKERNEL_ZIP_NAME:
        description: "File name (without .zip extension)"
        default: "N0kernel-munch"
        required: false
      ANYKERNEL_HYPEROS_DTBO:
        description: "Use DTBO for HyperOS/MIUI for AnyKernel"
        type: boolean
        default: false

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Display Inputs
        run: |
          echo "::group::Inputs"
          echo "Kernel Tree: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
          echo "Add KernelSU: ${{ github.event.inputs.ADD_KERNELSU }}"
          echo "KernelSU Setup URL": ${{ github.event.inputs.KERNELSU_SETUP_URL }}
          echo "KernelSU Branch": ${{ github.event.inputs.KERNELSU_SETUP_BRANCH }}
          echo "Create AnyKernel: ${{ github.event.inputs.CREATE_ANYKERNEL }}"
          echo "AnyKernel URL: ${{ github.event.inputs.ANYKERNEL_URL }}/tree/${{ github.event.inputs.ANYKERNEL_BRANCH }}"
          echo "Use DTBO for HyperOS/MIUI for AnyKernel": ${{ github.event.inputs.ANYKERNEL_HYPEROS_DTBO }}
          echo "::endgroup::"

      - name: Cache Clang
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: clang
          key: clang-r547379
          restore-keys: |
            clang-

      - name: Download and Extract Clang (if not cached)
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
          mkdir -p clang
          tar -xf clang.tar.gz -C clang
          rm clang.tar.gz

      - name: Initialize workspace
        run: |
          echo "tools_folder=$(pwd)" >> $GITHUB_OUTPUT
          sudo apt install flex libncurses6 -y
          git clone --depth=1 ${{ github.event.inputs.KERNEL_TREE }} -b ${{ github.event.inputs.KERNEL_TREE_BRANCH }} kernel_tree
          echo "kernel_folder=$(pwd)/kernel_tree" >> $GITHUB_OUTPUT
        id: workspace

      - name: Building kernel
        run: |
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="never"
          export KBUILD_BUILD_HOST="worry"

          if [ ${{ github.event.inputs.ADD_KERNELSU }} == 'true' ]; then
            curl -LSs "${{ github.event.inputs.KERNELSU_SETUP_URL }}" | bash -s ${{ github.event.inputs.KERNELSU_SETUP_BRANCH }}
          fi

          make O=out vendor/munch_defconfig PATH="${{ steps.workspace.outputs.tools_folder }}/clang/bin:$PATH"
          make O=out CC=clang -j$(nproc --all) PATH="${{ steps.workspace.outputs.tools_folder }}/clang/bin:$PATH" CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1
        working-directory: ${{ steps.workspace.outputs.kernel_folder }}

      - name: "Upload Image.gz"
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz
          path: ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/Image.gz
      - name: "Upload dtb"
        uses: actions/upload-artifact@v4
        with:
          name: dtb
          path: ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/dtb.img
      - name: "Upload dtbo.img (AOSP)"
        uses: actions/upload-artifact@v4
        with:
          name: dtbo.img
          path: ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/dtbo.img

      - name: AnyKernel3
        if: ${{ success() && github.event.inputs.CREATE_ANYKERNEL == 'true' }}
        run: |
          git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b ${{ github.event.inputs.ANYKERNEL_BRANCH }} AnyKernel3
          if [ -e "Image.gz" ]; then
            cp -f Image.gz AnyKernel3
          fi
          if [ -e "dtb.img" ]; then
            cp -f dtb.img AnyKernel3/dtb
          fi
          if [ -e "dtbo.img" ] && [ ${{ github.event.inputs.ANYKERNEL_HYPEROS_DTBO }} != "true" ]; then
            cp -f dtbo.img AnyKernel3
          fi
          cd AnyKernel3
          zip -q -r "${{ github.event.inputs.ANYKERNEL_ZIP_NAME }}.zip" *
          mv "${{ github.event.inputs.ANYKERNEL_ZIP_NAME }}.zip" ../
        working-directory: ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/
      - name: "Upload AnyKernel"
        uses: actions/upload-artifact@v4
        if: ${{ success() && github.event.inputs.CREATE_ANYKERNEL == 'true'}}
        with:
          name: ${{ github.event.inputs.ANYKERNEL_ZIP_NAME }}
          path: |
            ${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/AnyKernel3/
            !${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/AnyKernel3/.git
            !${{ steps.workspace.outputs.kernel_folder }}/out/arch/arm64/boot/AnyKernel3/.github
